export const STARTING_REQUEST_OVERVIEW = 'STARTING_REQUEST_OVERVIEW';
export const FINISHED_REQUEST_OVERVIEW = 'FINISHED_REQUEST_OVERVIEW';

export const STARTING_REQUEST_USER = 'STARTING_REQUEST_USER';
export const FINISHED_REQUEST_USER = 'FINSIHED_REQUEST_USER';

export const STARTING_REQUEST_SESSION = 'STARTING_REQUEST_SESSION';
export const FINISHED_REQUEST_SESSION = 'FINISHED_REQUEST_SESSION';

export const ROUTE_CHANGE_TO_USER = 'ROUTE_CHANGE_TO_USER';
export const ROUTE_CHANGE_TO_SESSION = 'ROUTE_CHANGE_TO_SESSION';
export const ROUTE_CHANGE_TO_EVENTS = 'ROUTE_CHANGE_TO_EVENTS';
